# Buildpack API version
api = "0.8"

# Buildpack ID and metadata
[buildpack]
id = "samples/hello-processes-old"
version = "0.0.1"
name = "Hello Processes Buildpack"
homepage = "https://github.com/buildpacks/samples/tree/main/buildpacks/hello-process"

# Stacks that the buildpack will work with
[[stacks]]
id = "*"
